### ISSUE TITLE
CI script cannot access project nuget token

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/relay#108]
@joemcbride Please authorize the `graphql-dotnet/relay` project to access the `NUGET_AUTH_TOKEN` organization secret.  Thanks!

See issue below:

![image](https://user-images.githubusercontent.com/6377684/117073983-b8fb1500-ad00-11eb-9e6b-5fd834a4811e.png)

**Comment by joemcbride** [comment]
This is done.

**Comment by Shane32** [comment]
Thanks @joemcbride ! The key doesn’t have permission to publish GraphQL.Relay packages to NuGet. Can you help with that? Or do we need a token from @jquense  ?
