### ISSUE TITLE
Update to GraphQL v5

### ISSUE THREAD

**Issue by myty** [graphql-dotnet/relay#125]
To keep this repo in sync with the latest version of GraphQL, it should be updated to version 5 as well as .NET 6.

**Comment by sungam3r** [comment]
@Shane32 What do you think? I can update.

**Comment by Shane32** [comment]
Whatever you think is fine with me.

**Comment by Shane32** [comment]
In general, I don't use this repo because my data is stored in databases, not in memory.  And it wouldn't make sense to request a full table dump from the database and then separate it before returning it.  So I would think this repo needs IQueryable support to actually be useful for most people. See #121

**Comment by sungam3r** [comment]
I also don't use it but I have some plans to use in future.

**Comment by myty** [comment]
> In general, I don't use this repo because my data is stored in databases, not in memory. And it wouldn't make sense to request a full table dump from the database and then separate it before returning it. So I would think this repo needs IQueryable support to actually be useful for most people. See #121

Since `IQueryable` inherits from `IEnumerable` wouldn't #121 already solve that issue?  At least that was my impression.  In my initial testing, by using `Skip` and `Take`, it was only pulling back the records that were needed, but I suppose I could be wrong on that.  I'll run some additional tests, just to be sure.

Are you suggesting that `IQueryable` is added in addition to `IEnumerable`?

**Comment by Shane32** [comment]
Once an `IQueryable` is "converted" to an `IEnumerable`, all future operations will occur in the C# code instead of within the database engine.

Sample:

```cs
public void Test()
{
    var query = _db.GetTable<Products>();
    // query is an IQueryable
    var list = Filter(query, 10);  // query is converted to an IEnumerable here
    // list is now an enumerable
    var data = list.ToList();
    // the "Take(10)" part is not sent to the database engine, and so SQL will
    // return all results, and C# will then only take the first 10 results
}

public IEnumerable<T> Filter<T>(IEnumerable<T> list, int count)
{
    return list.Take(count);
}
```

**Comment by Shane32** [comment]
It is also not possible to use `ToListAsync` on an `IEnumerable`.

**Comment by Shane32** [comment]
@myty I'm sorry I have not really looked at #121 at all recently

**Comment by myty** [comment]
> @myty I'm sorry I have not really looked at #121 at all recently, so maybe the PR includes support for `IQueryable`; not sure.

No problem.  I did some more testing, and you are correct. I say let's add `IQueryable` to this PR.
