### ISSUE TITLE
Complex list input types for mutations?

### ISSUE THREAD

**Issue by MartinDawson** [graphql-dotnet/relay#13]
How do we use complex input types for mutations?

    public class SaveSongInput : MutationInputGraphType
    {
        public SaveSongInput()
        {
            Name = nameof(SaveSongInput);
           
            Field<ListGraphType<ArtistInput>>("Artists");
        }
    }

    public class ArtistInput : InputObjectGraphType
    {
        public ArtistInput()
        {
            Name = nameof(ArtistInput);

            Field<IntGraphType>("id", "The existing artist id");
            Field<StringGraphType>("Artist", "The name of the new artist");
        }
    }

    public class SaveSongPayload : MutationPayloadGraphType
    {
        public SaveSongPayload()
        {
            Name = nameof(SaveSongPayload);
           
            Field<NonNullGraphType<SongPayload>>("song");
        }

        public override object MutateAndGetPayload(MutationInputs inputs, ResolveFieldContext<object> context)
        {           
            // What goes here?
            var artists = inputs.Get<>...
        }
    }

In standard graphql-dotnet I can do this: http://graphql-dotnet.github.io/graphql-dotnet/getting-started#arguments.

Thanks again for all the help.

**Comment by jquense** [comment]
You can do the same thing as in normal graphql-dotnet.  context, is the second argument and has "arguments" on it, and the Inputs type is a dictionary of dictionaries so you use whatever to turn it into something more structured (like Automapper)

**Comment by MartinDawson** [comment]
I'm afraid I'm still confused on how to convert dictionary of dictionary inputs to the type I want using `context.GetArgument`

What I would do in graphql-dotnet is create another class like:

```
public class SongArtist
{
    public int? Id { get; set; }
    public string Artist { get; set; }
}
```

And then map it by doing `context.GetArgument<List<SongArtist>>("artists");` but this won't work because the argument is just `inputs`.

**Comment by jquense** [comment]
You can use something like Automapper, or the simpler graphql-dotnet ToObject extension method to turn the inputs into a more specific type, like `inputs["artists"].ToObject<Whatever>()`

**Comment by MartinDawson** [comment]
@jquense Thanks a lot for pointing me in the right direction. Here's what I ended up with:

`var artists = inputs.Get("artists", new object[0]).Select(x => x.As<Dictionary<string, object>>().ToObject<ArtistInput>());`
