### ISSUE TITLE
Method not found: 'GraphQL.Types.EventStreamFieldType GraphQL.Builders.FieldBuilder`2.get_FieldType()'

### ISSUE THREAD

**Issue by thatham** [graphql-dotnet/relay#160]
Once we upgrade GraphQL.Server.Transports.AspNetCore library to version 6.1.0, I'm receiving above error implementing AsyncNodeGraphType abstraction.

Found that this (GraphQL.Relay) library is using GraphQL version 5.0.0 nupkg. Please help to upgrade to the latest version as this doesn't seems to release any latest version long time.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/relay/releases/tag/0.7.0 
https://github.com/graphql-dotnet/relay/issues/110

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/GraphQL.Relay/0.7.0#versions-body-tab published
