### ISSUE TITLE
Id() helper is slow

### ISSUE THREAD

**Issue by nbarbettini** [graphql-dotnet/relay#182]
When creating a GraphType derived from `GraphQL.Relay.Types.NodeGraphType`, using the `Id()` helper method causes a performance hit.

I assume it's because of `expression.Compile`: https://github.com/graphql-dotnet/relay/blob/master/src/GraphQL.Relay/Types/NodeGraphType.cs#L97

I did some rough timing on a project that returns a large GQL response. For 40k objects, the difference is:
```
With Id() helper:		3570ms
Without Id() helper:	574ms
```

**Comment by Shane32** [comment]
Yeah the `expression.Compile()` method should certainly be moved outside of the resolver.

**Comment by nbarbettini** [comment]
Thanks @Shane32!
