### ISSUE TITLE
Relay sample class

### ISSUE THREAD

**Issue by lcola** [graphql-dotnet/relay#3]
Hi @jquense , 
Could you explain me about DroidPayload, CreateDroidInput and DeleteDroidInput classes definition?
Implementing classes as in the example, it can be used directly in react?
Many thanks
lc

**Comment by jquense** [comment]
the mutation input classes describe the data coming from the client (specifically your relay client) and the payload is what the server returns after the mutation has run. neither are used in React, you need to write the client side part of the mutation in Javascript per the relay docs.

**Comment by mattmeye** [comment]
+1 i vote for a full example
