### ISSUE TITLE
Support GraphQL 3.0.0

### ISSUE THREAD

**Issue by barryhagan** [graphql-dotnet/relay#54]
There are breaking changes in GraphQL 3.0.0 that affect this project:

```
System.MissingMethodException: Method not found: 'GraphQL.Builders.FieldBuilder`2<!0,!1> GraphQL.Builders.FieldBuilder`2.Argument(System.String, System.String)'.
   at GraphQL.Relay.Types.QueryGraphType..ctor()
```

**Comment by sungam3r** [comment]
@barryhagan I updated the project to the latest GraphQL preview but I did not delve into the essence of the project.

**Comment by kimdv** [comment]
Hi @barryhagan ! 
I have also this problem with the 2.4.0 version. 

Did you something working with that version?

**Comment by kimdv** [comment]
@barryhagan maybe related to this: https://github.com/graphql-dotnet/relay/issues/7

**Comment by Shane32** [comment]
n/a after #80
