### ISSUE TITLE
Support GraphQL ^4.0.0

### ISSUE THREAD

**Issue by JoeHartzell** [graphql-dotnet/relay#79]
The documentation for how to use this project with graphql-dotnet seems to be outdated. Besides being outdated, this relay package seems to depending on graphql-dotnet 2.4.0. 

There is already an issue for updating to GraphQL 3.0.0 (#54). 

I have a fork updated to GraphQL 4.0.2, .net5.0, and running without issue. I fixed all of the breaking changes and updated the StarWars example project. Still working on fixing the tests. I would be more than happy to submit a PR for review.

I was curious what everyone's thoughts were on updating this project.

**Comment by Shane32** [comment]
Thanks for the effort @JoeHartzell !!
