### ISSUE TITLE
Dependency injection does not work for GraphTypes

### ISSUE THREAD

**Issue by tanekim77** [graphql-dotnet/relay#9]
Dependency injection of AppDbContext to the constructor of AppQuery works fine if UserType field has parameterless constructor, as shown below.
```
public class AppQuery : QueryGraphType
{
         private readonly AppDbContext _dbContext;
         public AppQuery(AppDbContext dbContext)
         {
                _dbContext = dbContext;
                 Name = "Query";
                 Field<UserType>(name: "viewer", resolve: context => dbContext.User.Find(1));
          }
 }

public class UserType : NodeGraphType<User>
 {
        public UserType()
        {
            Name = "User";
            Id(_ => _.Id);
            Field(_ => _.Name);
       }
       public override User GetById(string id)
        {
            return new User(){ Name="Bob" }
        }
}

```
But if I do dependency injection on the UserType's constructor like below, I get an error complaining that only parameter-less constructor is accepted. What I found was that when AppQuery is using ```Field <UserType>```, it is forcing itself to use parameter-less constructor in UserType.
To test this, you need to be using the latest version of Graphql-dotnet/Relay
```
 public class UserType : NodeGraphType<User>
    {
        public AppDbContext _dbContext;

        public UserType(AppDbContext dbContext)
        {
            _dbContext = dbContext;

            Name = "User";
            Id(_ => _.Id);
            Field(_ => _.Name);
        }

        public override User GetById(string id)
        {
            return _dbContext.Users.Find(id);
        }
    }
```

**Comment by jquense** [comment]
Something is probably misconfigured with you DI setup, The library here has no opinion or dependence on any DI approach., you can use ctor injection, That's what i'm using for projects (and I think the example apps here as well)

**Comment by tanekim77** [comment]
The examples in this repo is using very outdated version of this library. Perhaps the examples would not work if you update it to use the latest one. After looking at the stack trace, Field<UserType> is calling 
System.Activator.CreateInstance(Type type), which is trying to create an instance of UserType using parameteless constructor. If I remove Field <UserType> line from the code, everything works fine. 

Server.Controllers.GraphQLController:Error: GraphQL errors: GraphQL.ExecutionError: No parameterless constructor defined for this object. ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at GraphQL.Types.Schema.<CreateTypesLookup>b__56_0(Type t)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GraphQL.Types.Schema.CreateTypesLookup()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at GraphQL.Types.Schema.get_AllTypes()
   at GraphQL.Instrumentation.FieldMiddlewareBuilder.ApplyTo(ISchema schema)
   at GraphQL.DocumentExecuter.<ExecuteAsync>d__12.MoveNext()

**Comment by tanekim77** [comment]
I just tested the examples by using the latest version of the library. After downloading the examples from 
https://github.com/graphql-dotnet/relay
I deleted the folder GraphQL.Relay inside the src directory.
Then, I updated every libraries inside to the latest one.
I made sure it compiled without an error. Then when I ran, it is having errors. Please confirm.

**Comment by jquense** [comment]
I'm not sure what you mean. The examples reference the local code, building them from source, so they are using the latest possible version.
